networks:
  backend:

volumes:
  mssql_data:
    driver: local

services:

  backend:
    image: dory15/backend:v1.0.0
    environment:
      ENV: "prod"
      DB_STRING: "sqlserver://sa:Password12345@sqlserver:1433?database=Backend"
      PORT: "3000"
      JWT_SECRET: sadadasdasdasdasdasdas
      JWT_EXPIRATION: "150000"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - backend

  sqlserver:
    # image: mcr.microsoft.com/mssql/server:2022-latest
    image: dory15/backend_db:v1.0.0
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Password12345"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    hostname: sql1
    restart: always
    networks:
      - backend